### ISSUE TITLE
Neuron Mesh Download

### ISSUE THREAD

**Issue by CesiumChloride** [connectome-neuprint/neuprint-python#17]
Hello,

Is there a way to use neuprint-python to download neuron mesh from FlyEM database? Thanks!

**Comment by stuarteberg** [comment]
Unfortunately, no, there is currently no way to download neuron meshes from neuprint.  To download neuron meshes, you will have to download them from either DVID or the precomputed neuroglancer meshes.

The [cloud-volume][1] open source project supports downloading meshes from a precomputed neuroglancer store.  Here's an example that downloads 2 meshes, at reduced size and level-of-detail (`lod=2`):

```python
In [45]: from cloudvolume import CloudVolume

In [46]: vol = CloudVolume('gs://neuroglancer-janelia-flyem-hemibrain/v1.1/segmentation')

In [47]: meshes = vol.mesh.get([1944507292, 636789080], lod=2)

In [48]: for body_id, mesh in meshes.items():
    ...:     with open(f'/tmp/{body_id}.obj', 'wb') as f:
    ...:         f.write(mesh.to_obj())
    ...:
```

[1]: https://github.com/seung-lab/cloud-volume

**Comment by CesiumChloride** [comment]
Thanks! 

I had some experience using cloud-volume with FlyWire with their chunked-graph tokens, but do you know where I can get the Google credentials for FlyEM database?

**Comment by stuarteberg** [comment]
I don’t think you need any.

**Comment by CesiumChloride** [comment]
Oh yes, that's true. Now I can successfully download the mesh. Thanks!

**Comment by stuarteberg** [comment]
Out-of-scope.  Use alternative projects as described above. Closing.
