### ISSUE TITLE
Issues with simulation on Mac

### ISSUE THREAD

**Issue by 0xJustin** [connectome-neuprint/neuprint-python#20]
Hi, I've been using neuprint to pull from Hemibrain for some months now without issue
I have been attempting to compartmentalize neurons in the EPG using the simulation tools: https://connectome-neuprint.github.io/neuprint-python/docs/notebooks/SimulationTutorial.html 
But, I am running into errors on Mac 10.15.7
When I run `res = nm.simulate(2)` I receive the error:
BrokenPipeError: [Errno 32] Broken pipe
![image](https://user-images.githubusercontent.com/39317523/99736871-1eca4c00-2a95-11eb-87ee-62cb8a6538b4.png)
I messed around a bit with the line in `simulation.py` that errors out and found that the binary string created in `self.spice_model` is too large and causes an error. Is this an issue with Mac? Is the spice model failing somewhere? Thanks for your help.

**Comment by stuarteberg** [comment]
I'm not able to reproduce the problem, but I did notice a minor issue with the line shown in your traceback above.

The Python documentation recommends against using `p.stdin.write()`.  It favors `p.communicate()`, so I've changed that line and published a new version of `neuprint-python`.  If we're lucky, maybe that will fix the problem you're seeing.  Can you give it a try?

```
conda install -c flyem-forge -c conda-forge `neuprint-python>=0.4.12`
```

**Comment by 0xJustin** [comment]
Hi again, I hope you had a good holiday. The push you added fixed my problem! But now I have a new one
![image](https://user-images.githubusercontent.com/39317523/100675179-75a51080-3334-11eb-89c6-863c2c8284cd.png)
I am using code identical to the first 3 cells here:
https://connectome-neuprint.github.io/neuprint-python/docs/notebooks/SimulationTutorial.html#Setup-neuron-model 
Based on the source code it seems like the `os.fdopen` is not receiving any data, I think
Thanks again

**Comment by stuarteberg** [comment]
Sorry you're still running into trouble.  I'm not able to reproduce the error.  The following code works on my Mac:

```python
from neuprint import Client, NeuronModel
client = Client("neuprint.janelia.org", "hemibrain:v1.0.1")
nm = NeuronModel(449438847)
res = nm.simulate(2)
```

Can you please run the following command and attach the resulting yaml file here?

```
conda env export -n subneuron_env -f subneuron.yaml
```

**Comment by 0xJustin** [comment]
I uninstalled python and conda, and reinstalled in a new conda environment and it worked! I think when one of my packages updated for python3.9 it may have broke something. Thanks for your help!

**Comment by stuarteberg** [comment]
OK, I haven't personally tested with Python 3.8 or 3.9, so let us know if you run into any problems.  I don't expect any compatibility issues with newer python versions, but surprises can happen sometimes.
