### ISSUE TITLE
Cannot reproduce docstring example in fetch_mitochondria

### ISSUE THREAD

**Issue by miridyson** [connectome-neuprint/neuprint-python#22]
### What

I am trying to fetch volume of mitochondria within neurons with some custom code using your API. The same code I wrote a couple of months ago has stopped working. I went back to your documentation and tried to at least reproduce the `fetch_mitochondria` docstring https://github.com/connectome-neuprint/neuprint-python/blob/1a3e7db4c488cebe9df2ffdd690006e24112c91a/neuprint/queries.py#L1346.
But I cannot even reproduce that anymore.

### Environment
**OS**
Ubuntu 18.04
**Packages**
conda 4.9.2
python 3.7.8
Full details in the environment.yml, which should be a clone of https://github.com/connectome-neuprint/neuprint-python/blob/master/environment.yml
[neuprint_environment.yml.zip](https://github.com/connectome-neuprint/neuprint-python/files/6213051/neuprint_environment.yml.zip)

### Steps to replicate my issue

Bash
```
# Download the repository
git clone https://github.com/connectome-neuprint/neuprint-python
# Enter the repository
cd neuprint-python
# Create an environment with the right packages and versions
conda create --name neuprint -f environment.yml
# In order to use this environment in Jupyter
conda install ipykernel
python -m ipykernel install --user --name neuprint --display-name neuprint
```
Python
```
# Then I ran this in a Jupyter cell
from neuprint import Client, NeuronCriteria as NC, fetch_neurons, fetch_mitochondria
# token is confidential
c = Client('neuprint.janelia.org', dataset='hemibrain:v1.2', token=token)
c.fetch_version()
# 0.1.0

# Try to run the example in
# https://github.com/connectome-neuprint/neuprint-python/blob/1a3e7db4c488cebe9df2ffdd690006e24112c91a/neuprint/queries.py#L1346
# (I have changed Synapse with Mito criteria)

from neuprint import NeuronCriteria as NC, MitoCriteria as MC, fetch_synapses

nc = NC(type='ExR.*', regex=True, rois=['EB'])
mc = MC(rois=['FB', 'LAL(R)'], size=100_000)
fetch_mitochondria(nc, mc)
```

After running the above, I get a tqdm progress bar and the resulting table (empty)

  | bodyId | mitoType | roi | x | y | z | size | r0 | r1 | r2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Do you know what's the issue? Don't hesitate to ask more information if I was not comprehensive enough! :)

Thanks,
Miranda

**Comment by stuarteberg** [comment]
Hi Miranda,

Sorry for the confusion here.  We consider the mitochondria data model to be "alpha" or "beta" quality, i.e. subject to minor changes.  We should have been clearer about this in our [release notes](https://docs.google.com/document/d/1vae3ClHR8z8uekqwrOHtqiux3oY5-Y_xw6W2srCi3PI/edit#heading=h.e8e66lv0jly7).  My mistake.

A few days ago, we made some minor changes to the data model, but I haven't yet released an update to the `neuprint-python` bindings.  I will do so later today, and post an update here.  After that, you can upgrade the package locally and the function will work again.

**Comment by stuarteberg** [comment]
I've published a new release of `neuprint-python`, version `0.4.14`.  You can install it with the following command:

```bash
conda install -c flyem-forge -c conda-forge 'neuprint-python>=0.4.14'
```

Thanks for the thorough bug report!

**Comment by stuarteberg** [comment]
BTW, Please note that  we changed the column data in the `mitoType` field.  Instead of numbers (`1`, `3`, `2`), we now use strings (`dark`, `medium`, `light`).  There is a small chance these strings might be replaced with something more biologically descriptive in the future.

**Comment by miridyson** [comment]
Thank you so much for your help and responsiveness!!

**Comment by miridyson** [comment]
It works now!
