### ISSUE TITLE
Possible Bug in Tutorial

### ISSUE THREAD

**Issue by unidesigner** [connectome-neuprint/neuprint-python#26]
In the [tutorial on fetching upstream/downstream partners](https://connectome-neuprint.github.io/neuprint-python/docs/notebooks/QueryTutorial.html#Fetch-connections) I think the query for "# Example: Fetch all downstream connections FROM a set of neurons" actually fetches the upstream connections, if I compare this with neuprint UI outputs. Can you confirm that this may be the cause? I can also provide an example if necessary.

**Comment by stuarteberg** [comment]
As far as I can tell, the tutorial is correct, and consistent with the website results as far as I can tell.

Here's the tutorial example:

```python
from neuprint import fetch_adjacencies, NeuronCriteria as NC

# Example: Fetch all downstream connections FROM a set of neurons
neuron_df, conn_df = fetch_adjacencies([387023620, 387364605, 416642425], None)
```

Using [`setup_debug_logging()`][1], I can see the cypher query that gets generated.  After some simplification, it's basically the following, which looks correct to me:


```cypher
MATCH (n:Segment)-[e:ConnectsTo]->(m:Neuron)
WHERE n.bodyId in [387023620, 387364605, 416642425]
RETURN n.bodyId as bodyId_pre,
       m.bodyId as bodyId_post,
       e.weight as weight,
       e.roiInfo as roiInfo
```

[1]: https://connectome-neuprint.github.io/neuprint-python/docs/client.html#neuprint.client.setup_debug_logging

If you can provide an example neuprint link that seems to contradict the python results, I'd like to look at it.

**Comment by unidesigner** [comment]
Indeed, it is correct. I made a mistake in my code. Sorry for the noise. It's useful to know about `setup_debug_logging()`.
