### ISSUE TITLE
How are segments obtained in the skeleton representation?

### ISSUE THREAD

**Issue by lukablagoje** [connectome-neuprint/neuprint-python#28]
Hi, I'm trying to recreate realistic neurons using the skeleton data, but I'm not sure how exactly to connect the segments. More specifically, what is the meaning of skeleton radius? Is it like a cylinder radius?

**Comment by stuarteberg** [comment]
>what is the meaning of skeleton radius? Is it like a cylinder radius?

Yes, it's an estimate of the radius of the neurite at that particular point in the skeleton.

Related discussions and references:

- https://groups.google.com/g/neuprint/c/1FTsFbNVWR8
- https://groups.google.com/g/neuprint/c/5kZ69THuNdI
- https://homepages.inf.ed.ac.uk/rbf/HIPR2/distance.htm
