### ISSUE TITLE
Philipp's fork

### ISSUE THREAD

**Issue by stuarteberg** [connectome-neuprint/neuprint-python#3]
@schlegelp 

Hi Philipp!

Whoops!  In the past week or so, you and I have independently been making significant changes to `neuprint-python` within our own forks ([yours][] and [mine][]).  Sorry I didn't loop you in while I was working on my changes

To make matters even more confusing, I made several minor releases in the past week, and changed the API multiple times between releases.  If you already examined some of last week's changes, you may need to have a second look.

[yours]: https://github.com/schlegelp/neuprint-python
[mine]: https://github.com/connectome-neuprint/neuprint-python

What should we do to reconcile our forks?

Of course, they both contain a lot of overlapping functionality, but there are significant differences at this point.  I am not finished adding functionality to the main fork, but here's what I've done so far:

- `Client` now contains methods for all ["built in" server endpoints][1]
- `dataset` is no longer an argument to individual query functions.  Instead, users must specify the `dataset` name when `Client` is constructed.
- Query functions will use the default (global) client if none is explicitly provided. (Your fork does this, too.)
- I've added support for several common queries.  I tried to use names that are similar to the corresponding functionality on the Neuprint Explorer site.  Some important queries are still missing, notably synapse queries.
- (This is the biggest difference between our forks.) Where possible, individual search criteria (e.g. `bodyId`, `type`, etc.) are not passed in as individual arguments to each function.  Instead, all neuron filtering criteria has been moved into a [separate class][2].  For example, see [`fetch_simple_connections()`][3].  The search criteria also allows user to restrict the search to a set of input or output ROIs, optionally thresholded by a minimum synapse count.  For instance, there is no separate function for `fetch_connetivity_in_roi()`, because that functionality is built-in to the general-purpose `fetch_neurons()` function.
- In `fetch_neurons`, I don't ask the user to choose which properties to return.  Instead, all properties are returned, and and the user should drop the columns they don't need.  (This comes with a performance penalty, so I may change this in the future.)
- I used f-strings with impunity throughout the code, so `neuprint-python` now requires Python >= 3.6.

Here are our options, as I see them:

1. We add your fork's additional features (e.g. synapse queries) to the main fork, and deprecate your fork.  (I'm not sure what to do about your `navis`-related functions.)  However, if you're locked in to Python 3.5, or the new API doesn't suit your needs, this may not be a feasible option for you.  Another problem is that there is a name conflict between my `fetch_neurons()` and your `fetch_neurons()` function, which does something different.

2. Alternatively, you could just rename your fork, to avoid confusing `neuprint-python` users who might accidentally stumble upon the wrong documentation pages.  This is not my preference, but I understand if you're working with constraints that preclude option 1 (especially when it comes to the Python version.)

3. Here's an intriguing idea: We implement option 1, but we build packages for Python 3.5 by post-processing the source code using [f2format][].  I have never used that tool (I only discovered it 10 seconds ago), but if it works well, it might be the best way forward.  (Other than f-strings, I don't think I'm using any Python features that aren't supported in Python 3.5.)

[f2format]: https://github.com/pybpc/f2format

So, what do you think?

PS -- Sadly, I'm quite busy for the next few days, but I can devote more time to `neuprint-python` next week.  I just wanted to ping you now, in case you're still making improvements to your fork.

[1]: https://neuprint.janelia.org/help/api?dataset=hemibrain:v1.0
[2]: https://connectome-neuprint.github.io/neuprint-python/docs/segmentcriteria.html
[3]: https://connectome-neuprint.github.io/neuprint-python/docs/queries.html#neuprint.queries.fetch_simple_connections

**Comment by schlegelp** [comment]
Hi Stuart!

Absolutely my bad - I actually noticed the divergence but needed to do some rapid prototyping. Fortunately, I'm not locked into Python 3.5 and frankly I'd be happy to ditch it.  

My suggestion would be this:
1. I add new/modified functions in my fork to your main fork. Given the mess I caused by diverging I might just start from scratch there  -  hopefully it's mostly copy paste.
2. Any NAVis related function is moved to NAVis (it already contains interfaces to R, neuromorpho, etc) - basically NAVis would wrap neuprint instead of the other way around. 
3. To avoid future user confusion I could ditch my fork and work on my own branch of the main fork if that's OK with you? This is also how I imagined migrating stuff from my fork to yours.

How does that sound?

**Comment by stuarteberg** [comment]
> I'm not locked into Python 3.5

Ah, cool.  That makes things easier.

>I add new/modified functions in my fork to your main fork.

Sounds good.  I'll try to respond quickly to any PRs you create.  I'll also try not to break the library API any more, as long as no users hate it currently.

>To avoid future user confusion I could ditch my fork and work on my own branch

Yeah, I guess the easiest thing is to reset your repo's master branch to be in sync with the main fork, and then use it as the basis for future pull requests.  The only thing that needs to be deleted per se is the documentation on `readthedocs.com`. (The new docs are just hosted on "github pages".)

**Comment by schlegelp** [comment]
Just a heads up: I removed my fork + its page on readthedocs, and made a fresh fork for myself.

Currently trying to figure out how to integrate functions I've had in my old neuprint-python with yours without duplicating any functionality.

I thought I'd use this thread to list potential conflicts and solicit your input.

**Comment by schlegelp** [comment]
First up: `fetch_adjacencies`
https://github.com/connectome-neuprint/neuprint-python/blob/341312d5c243e39a0c0601bf7311171e976d933c/neuprint/queries.py#L501

In its current form this function returns only downstream partners* of the query neurons. I had a similar function that would let you define `sources` and `targets` separately. If either parameter was `None` it would fetch all downstream or upstream partners, respectively. Would you mind if I changed `fetch_adjacencies` to do something similar?

\* it also appears to filter for `Traced` and not `cropped` from what I can tell: https://github.com/connectome-neuprint/neuprint-python/blob/341312d5c243e39a0c0601bf7311171e976d933c/neuprint/queries.py#L558
Is this intended?

**Comment by stuarteberg** [comment]
>First up: `fetch_adjacencies`

Ah, yes, this is a bit of a mess.  Thanks for starting the discussion.

I ended up implementing multiple functions:

- `fetch_simple_connections()` allows you to specify sources and targets (upstream and downstream) and behaves as your function does.  (It is named this way because "Simple Connections" is the name used in the neuprint explorer site.)

- `fetch_adjacencies()` is similar, but was intended for people who want to download a huge adjacency set and then do their analysis offline (without neuprint).  It adds three features:
   - It fetches the results in batches to avoid timeouts.
   - It parses the roiInfo (but discards non-primary ROIs to avoid confusion).
   - It optionally dumps the results to disk.

- `fetch_traced_adjacencies` is merely a convenience function for calling the above with `status="Traced"` and `cropped=False`.  The only reason it exists is that this function is referenced elsewhere, in external documentation, so I want it to remain in the API.

I don't like the fact that I have two functions with very similar functionality.  I should probably unify them.  That just requires adding the above feature list to `fetch_simple_connections()`.

Finally: 

>it also appears to filter for `Traced` and not `cropped` from what I can tell

Crap! Thanks for pointing that out.  I should fix that immediately.

**Comment by stuarteberg** [comment]
>>it also appears to filter for `Traced` and not `cropped` from what I can tell

>Crap! Thanks for pointing that out.  I should fix that immediately.

OK, I've pushed a fix and published release `0.3.4`.

**Comment by schlegelp** [comment]
Cool! Mind if I make a quick small pull requests? Just want to make sure the code I write generally lines up with how you want things to go before I add more stuff.

**Comment by stuarteberg** [comment]
Sure, go ahead.

**Comment by schlegelp** [comment]
Not sure why the build on my pull request fails - it seems to not find the credentials (i.e. token) which I presume is saved to an environment variable. I would have thought Travis simply reuses your build environment for pull requests but maybe it doesn't? I can't seem to set environment variables anywhere though.

On different note: I changed `fetch_adjacencies` such that you can pass `sources` and/or `targets`. Have a look at the commit and let me know what you think 4f18dd4927e5cb720a136c0d591549afec2d29ea

**Comment by stuarteberg** [comment]
>Not sure why the build on my pull request fails

Sorry about that.  The testing setup is not perfect at the moment.  the tests perform queries against the public neuprint server `neuprint.janelia.org` using my personal credentials, which are [encrypted and saved into the `.travis.yml` file][1].  Travis-CI refuses to decrypt such variables in the case of pull requests, since the PR author could steal the decrypted credentials.

I don't have a great solution for this problem.  For now, I'm afraid all pull requests (including my own) will fail to be tested.  But you can still [run the tests locally on your own machine][2], of course.

[1]: https://github.com/connectome-neuprint/neuprint-python/blob/master/.travis.yml#L8-L9
[2]: https://connectome-neuprint.github.io/neuprint-python/docs/development.html#tests

**Comment by stuarteberg** [comment]
Closed via #5.
