### ISSUE TITLE
Is the data updated at any time?

### ISSUE THREAD

**Issue by urnotlcxz** [connectome-neuprint/neuprint-python#38]
Hi,I found that the data I obtained several month ago is different from the data I obtain today. The synapse number in the fixed connection has increased. So I want to ask that Is the data updated at any time?

Thanks!

**Comment by stuarteberg** [comment]
The data hasn't changed, but the behavior of `fetch_synapse_connections()` changed in [v0.4.17][1]. If you're using that function, the change might be responsible for the difference you're seeing.

Previously, synapse connections were only included in the results if BOTH sides of the synapse reside within the ROI(s) you specified.  But that wasn't consistent with the aggregate neuron-to-neuron connection weights, which are pre-loaded in the neuprint database using only the post-synaptic ROI.  The [new behavior][2] is more consistent.

[1]: https://connectome-neuprint.github.io/neuprint-python/docs/changelog.html#id9
[2]: https://github.com/connectome-neuprint/neuprint-python/commit/d2584412fd8077e767617e935f52db23edbec70f

**Comment by urnotlcxz** [comment]
I used `fetch_adjacencies()` , which is probably affected by `fetch_synapse_connections()`.
Thank you very much for your reply.

**Comment by stuarteberg** [comment]
I don't think the behavior of `fetch_adjacencies()` should have changed in recent months.

- What version of the hemibrain dataset have you been using?
- What version of neuprint-python have you been using?
- Have you switched to a newer version of either recently?
- You mentioned that the results from "several months ago" were different.  Do you recall exactly how long ago that was?
- Can you provide an example code snippet that produces different results today than it did previously?

**Comment by urnotlcxz** [comment]
I think I figured out why. The Neuron Criteria is a little different. I guess it was my mistake. I'm sorry.
- The hemibrain dataset version is **v1.2.1**
- Te neuprint.__version__ is **0.4.25**
Here is an example:
```
from neuprint import NeuronCriteria as NC
ORN_criteria = NC(status='Traced', type='.*ORN.*')  
PN_criteria = NC(status='Traced', type='.*PN.*', cropped=False,regex=True)
ORN_PN_neurons, ORN_PN_roi = fetch_adjacencies(ORN_criteria, PN_criteria)  
ORN_PN_conn = merge_neuron_properties(ORN_PN_neurons, ORN_PN_roi, ['type'])  
```
There are **16219** connections from ORN to PN (ORN_PN_conn) obtained directly. But when I delete `cropped=False` in PN_criteria,the number of connections is **17357**.
The neurons that are not cropped are more than cropped.

Sorry again and Thanks a lot!
