### ISSUE TITLE
Support more Neuron properties

### ISSUE THREAD

**Issue by stuarteberg** [connectome-neuprint/neuprint-python#39]
The upcoming MANC release will have more properties than we had in the hemibrain, such as `group`.  We need to add support for those in `NeuronCriteria`.

We might want to do a bit of refactoring to make it possible to support arbitrary keywords for properties which we haven't explicitly written support for.

Related: Although we already support `somaSide`, we should change it from a "single value" property to a "value list property" similar to `type`, `status`, `class_`, etc.

**Comment by umayaml** [comment]
How would you like to implement arbitrary keywords for properties. Looking at the list of Neuron properties for MANC and there seems to be way too many to implement in the current fashion for NeuronCriteria.

**Comment by stuarteberg** [comment]
I think the current method is all we have to go with for now. I admit it needs stone sort of refactoring. If you have any ideas, I’m open to discuss.

**Comment by stuarteberg** [comment]
Closed via commits 72af6b5acb6412ab1d03e445396e9e30b34f96f8...c97f6dd4c30d4823c4842f5a1a445ff939f7db49
