### ISSUE TITLE
error converting table to matrix

### ISSUE THREAD

**Issue by artxz** [connectome-neuprint/neuprint-python#48]
running the example (https://connectome-neuprint.github.io/neuprint-python/docs/utils.html#neuprint.utils.connection_table_to_matrix) returns this error

```
TypeError                                 Traceback (most recent call last)
Cell In[49], line 2
      1 from neuprint.utils import connection_table_to_matrix
----> 2 connection_table_to_matrix(conn_df, 'type')

File [c:\Users\zhaoa\Envs\ol-connectome\lib\site-packages\neuprint\utils.py:304](file:///C:/Users/zhaoa/Envs/ol-connectome/lib/site-packages/neuprint/utils.py:304), in connection_table_to_matrix(conn_df, group_cols, weight_col, sort_by, make_square)
    301 dtype = conn_df[weight_col].dtype
    303 agg_weights_df = conn_df.groupby([col_pre, col_post], sort=False)[weight_col].sum().reset_index()
--> 304 matrix = agg_weights_df.pivot(col_pre, col_post, weight_col)
    305 matrix = matrix.fillna(0).astype(dtype)
    307 if sort_by:

TypeError: DataFrame.pivot() takes 1 positional argument but 4 were given

```

**Comment by stuarteberg** [comment]
This is due to a change in the pandas API. I’ve fixed this on the master branch of neuprint-python, but haven’t yet made a new release. You may have to downgrade to pandas 1.x for now.

**Comment by artxz** [comment]
sorry, had another look, it seems the problem is not `groupby` but the next line
`matrix = agg_weights_df.pivot(col_pre, col_post, weight_col)`

**Comment by stuarteberg** [comment]
Right, that’s the line I changed on the master branch.

**Comment by artxz** [comment]
just to be sure, you meant this ?
https://github.com/connectome-neuprint/neuprint-python/blob/7e200bf2efd27ff20480f6a08c9c1356528b4f13/neuprint/utils.py#L304C6-L304C6

I'm up to date with this branch. 

On the other hand, this works for me 
`matrix = agg_weights_df.pivot(index=col_pre, columns=col_post, values=weight_col)`

**Comment by stuarteberg** [comment]
Your link is to an older version. (The docs link to the released version.)

Here's the current version:
https://github.com/connectome-neuprint/neuprint-python/blob/0dcd00b3543362618572b2f7799ed1473d0f7acd/neuprint/utils.py#L304C86-L304C86
